name: Decision
description: "Start a discussion or document a decision.
title: "[Decision]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Let's document your decision cleanly! This template is based on [MADR](https://adr.github.io/madr/)".
  - type: input
    id: status
    attributes:
      label: Status
      description: "Are you proposing this decision or is it already accepted? "
      value: proposed
      placeholder: "{proposed | rejected | accepted | deprecated | ... | superseded by [ADR-0005](0005-example.md)}"
    validations:
      required: false
  - type: textarea
    id: context-and-problem-statement
    attributes:
      label: Context and Problem Statement
      description: >
        Describe the context and problem statement, e.g., in free form using two to three sentences or in the form of an illustrative story.
        You may want to articulate the problem in form of a question and add links to collaboration boards or issue management systems.
      placeholder: "Problem X occured. How do we solve X?"
    validations:
      required: true
  - type: textarea
    id: decision-drives
    attributes:
      label: Decision Drivers
      description: "Decision drivers are forces or facing concerns that drive the decision. (Smart sentence!)"
      placeholder: |
        * {decision driver 1, e.g., a force, facing concern, …}
        * {decision driver 2, e.g., a force, facing concern, …}
  - type: textarea
    id: considered-options
    attributes:
      label: Considered Options
      description: >
        The solutions you considered or suggest. Maybe someone will come up with an even better one?
      placeholder: |
        * {option 1}
        * {option 2}
    validations:
      required: true
  - type: textarea
    id: decision-outcome
    attributes:
      label: Decision Outcome
      description: >
        "If applicable, the chosen option and a short justification. The chosen option should match one of the options listed above.
        If you haven't decided yet, leave this field blank."
      placeholder: >
        Chosen option: "{option 1}", because {justification. e.g., only option, which meets k.o. criterion decision driver 
        | which resolves force {force} | … | comes out best (see below)}.
      value: >
        Chosen option: "", because
  - type: textarea
    id: pros-and-cons
    attributes:
      label: Pro and Cons of the Options
      description: >
        More detailed discussion of each option.
      placeholder: |
        #### {option 1}
        
        {example | description | pointer to more information | …} <!-- This is an optional element. Feel free to remove. -->

        * Good, because {argument a}
        * Good, because {argument b}
        * Bad, because {argument c}
        * … <!-- numbers of pros and cons can vary -->
      value: |
        #### {option 1}
        
        * Good, because 
        * Bad, because 
  - type: textarea
    id: more-information
    attributes:
      label: More information
      description: >
        If you have anything else to add, this is the place!
        
        You might want to provide additional evidence/confidence for the decision outcome here and/or
        document the team agreement on the decision and/or
        define when this decision when and how the decision should be realized and if/when it should be re-visited and/or
        how the decision is validated.
        Links to other decisions and resources might here appear as well.
      placeholder: >
        Replace me by useful information!
